runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app

libraries:
- name: numpy
  version: "1.6.1"
- name: PIL
  version: "1.1.7"
- name: flask
  version: "0.12"
- name: werkzeug
  version: "0.11.10"
- name: ssl
  version: latest

env_variables:
    CLOUD_STORAGE_BUCKET: connoixer-183213.appspot.com
